### PR TITLE
Added feature to convert images to pdf (#7)

### PR DESCRIPTION
**Pull request by pantuts**
In *nix systems, ImageMagick (convert) will be used to convert images to pdf.

### CODE REVIEW

**Comment by ritiek** [comment]
Let's use a cross platform solution so that it can work on all python supported systems including Windows and not just *nix. [FPDF](https://stackoverflow.com/a/27327984) module looks promising for image to PDF conversion. :smile:

Do not worry about the failing tests, I need to fix them. :wink:

**Comment by pantuts** [comment]
Got it. Will try to implement FPDF.

**Comment by pantuts** [comment]
I can't make fpdf output like ImageMagick. The conversion in fpdf is not really good.

**Comment by ritiek** [comment]
You're right, FPDF indeed seems to mess up.
However, I just tried out [img2pdf](https://pypi.python.org/pypi/img2pdf) and it seems to be converting fine. So, let's just stick to that.

**Comment by pantuts** [comment]
I have an update: https://github.com/pantuts/scribd-downloader/commit/7d7f12d0d20f9ccd1e35a54648dd830b3b5eeac8

I'm not sure how to reopen this with latest commit.

**Comment by ritiek** [comment]
It seems like you force pushed to your branch. In that case, leave this PR closed and open a new one.

**Comment by pantuts** [comment]
Thanks, done new pull request.

**Pull request closed without merging**
