### PR TITLE
Read Scribd account credentials from file

### LINKED ISSUE #40: Add username and password based authentication
...instead of relying on cookies extracted from premium-account session.

### PR DESCRIPTION
**Pull request by ritiek**
Closes #40.

### CODE REVIEW

**Comment by cedatif** [comment]
Hi,
Very good job ! But you don't grab the X-CSRF-Token ? This is no longer useful ?

thanks !

**Comment by ritiek** [comment]
Yep, that needs to be done for downloading books. This PR is still a
work-in-progress.

**Comment by cedatif** [comment]
```shell
## Return crsf_token with Login and Password
curl -X "POST" "https://www.scribd.com/csrf_token" \
     -H 'Accept-Encoding: gzip' \
     -H 'X-Requested-With: XMLHttpRequest' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "login_password": "PassWord",
  "login_or_email": "loginOrEmail"
}'

## Response 
{"csrf_token":"token"}
```

I tried many link and this one return a token.
This might be helpful ?

**Comment by ritiek** [comment]
@cedatif Yup, thanks! That's right. I also noticed that a CSRF token is also embedded in the HTML page of the book itself.  However, I decided to go with that specific URL as I think it's more stable that way.

----------

For anyone interested in what happened in the last commit (0f41f039de49be503c1a54274a19096d2d16ccd9):

The process is to fetch premium book content is:
Scribd Login -> CSRF Token -> Access Token -> Book Content.

I was unable to gain access to premium book content even when using premium session cookies. Turns out that we need to make a GET request to https://scribd.com/login and then Scribd will set some cookies, then we need to pass this cookies while making the POST request to login with premium credentials (username & pass) to Scribd. Then Scribd generates cookies which can gain access to the correct CSRF token and in turn the correct Access Token. This Access Token then allows access to premium book content.

Without using the cookies from the GET request earlier, Scribd will return faulty cookies when the POST request to login has been made. These faulty cookies would then fetch the faulty CSRF Token which would in turn fetch the faulty Access Token which isn't permitted to gain access to premium book content.

It took me quite a while to find the problem. I wonder why Scribd takes such a long route?

**Comment by ritiek** [comment]
Okay, this should be ready to merge.

**Pull request merged**
